# test_generic_qubit.py
# meant to be run with 'pytest'
#
# This file is part of scqubits: a Python package for superconducting qubits,
# Quantum 5, 583 (2021). https://quantum-journal.org/papers/q-2021-11-17-583/
#
#    Copyright (c) 2019 and later, Jens Koch and Peter Groszkowski
#    All rights reserved.
#
#    This source code is licensed under the BSD-style license found in the
#    LICENSE file in the root directory of this source tree.
############################################################################

import numpy as np
import pytest

from scqubits.core.generic_qubit import GenericQubit


@pytest.fixture
def qubit():
    return GenericQubit(E=4.3)


class TestConstruction:
    def test_stores_energy_splitting(self, qubit):
        assert qubit.E == 4.3

    def test_truncated_dim_is_2(self, qubit):
        assert qubit.truncated_dim == 2

    def test_default_id_str_is_autogenerated(self, qubit):
        assert isinstance(qubit.id_str, str)
        assert len(qubit.id_str) > 0

    def test_explicit_id_str_is_preserved(self):
        qubit = GenericQubit(E=1.0, id_str="my_qubit")
        assert qubit.id_str == "my_qubit"


class TestDefaultParams:
    def test_returns_dict_with_E_key(self):
        params = GenericQubit.default_params()
        assert "E" in params
        assert isinstance(params["E"], float)

    def test_construct_from_default_params(self):
        qubit = GenericQubit(**GenericQubit.default_params())
        assert qubit.E == GenericQubit.default_params()["E"]


class TestHamiltonian:
    def test_shape_is_2x2(self, qubit):
        H = qubit.hamiltonian()
        assert H.shape == (2, 2)

    def test_is_hermitian(self, qubit):
        H = qubit.hamiltonian()
        assert np.allclose(H, H.conj().T)

    def test_equals_half_E_sigma_z(self, qubit):
        expected = 0.5 * qubit.E * np.diag([1.0, -1.0])
        assert np.allclose(qubit.hamiltonian(), expected)

    def test_hilbertdim_is_2(self, qubit):
        assert qubit.hilbertdim() == 2


class TestSpectrum:
    def test_eigenvals_are_plus_minus_half_E(self, qubit):
        evals = qubit.eigenvals()
        assert np.allclose(sorted(evals), [-qubit.E / 2, qubit.E / 2])

    def test_eigenvals_gap_equals_E(self, qubit):
        evals = qubit.eigenvals()
        assert np.isclose(evals[1] - evals[0], qubit.E)

    def test_eigenvals_ascending(self, qubit):
        evals = qubit.eigenvals()
        assert evals[0] <= evals[1]

    def test_eigensys_returns_orthonormal_basis(self, qubit):
        _, evecs = qubit.eigensys()
        overlap = evecs.conj().T @ evecs
        assert np.allclose(overlap, np.eye(2))

    def test_eigensys_diagonalizes_hamiltonian(self, qubit):
        evals, evecs = qubit.eigensys()
        H = qubit.hamiltonian()
        diagonalized = evecs.conj().T @ H @ evecs
        assert np.allclose(diagonalized, np.diag(evals))


class TestPauliOperators:
    def test_sigma_x_squared_is_identity(self, qubit):
        sx = qubit.sx_operator()
        assert np.allclose(sx @ sx, np.eye(2))

    def test_sigma_y_squared_is_identity(self, qubit):
        sy = qubit.sy_operator()
        assert np.allclose(sy @ sy, np.eye(2))

    def test_sigma_z_squared_is_identity(self, qubit):
        sz = qubit.sz_operator()
        assert np.allclose(sz @ sz, np.eye(2))

    def test_sx_sy_anticommute(self, qubit):
        sx = qubit.sx_operator()
        sy = qubit.sy_operator()
        assert np.allclose(sx @ sy + sy @ sx, np.zeros((2, 2)))

    def test_sx_sy_product_is_i_sz(self, qubit):
        sx = qubit.sx_operator()
        sy = qubit.sy_operator()
        sz = qubit.sz_operator()
        assert np.allclose(sx @ sy, 1j * sz)

    def test_sigma_plus_equals_sx_plus_i_sy_over_2(self, qubit):
        sp = qubit.sp_operator()
        sx = qubit.sx_operator()
        sy = qubit.sy_operator()
        assert np.allclose(sp, 0.5 * (sx + 1j * sy))

    def test_sigma_minus_equals_sx_minus_i_sy_over_2(self, qubit):
        sm = qubit.sm_operator()
        sx = qubit.sx_operator()
        sy = qubit.sy_operator()
        assert np.allclose(sm, 0.5 * (sx - 1j * sy))

    def test_sigma_plus_is_adjoint_of_sigma_minus(self, qubit):
        sp = qubit.sp_operator()
        sm = qubit.sm_operator()
        assert np.allclose(sp, sm.conj().T)


class TestMatrixElementTable:
    def test_sz_table_is_diagonal(self, qubit):
        table = qubit.matrixelement_table("sz_operator")
        off_diag = table - np.diag(np.diag(table))
        assert np.allclose(off_diag, np.zeros((2, 2)))

    def test_sx_table_is_off_diagonal(self, qubit):
        table = qubit.matrixelement_table("sx_operator")
        assert np.isclose(table[0, 0], 0)
        assert np.isclose(table[1, 1], 0)
        assert not np.isclose(table[0, 1], 0)


class TestNotImplemented:
    def test_create_raises(self):
        with pytest.raises(NotImplementedError):
            GenericQubit.create()

    def test_widget_raises(self, qubit):
        with pytest.raises(NotImplementedError):
            qubit.widget()
