# test_parametersweep.py
# meant to be run with 'pytest'
#
# This file is part of scqubits: a Python package for superconducting qubits,
# Quantum 5, 583 (2021). https://quantum-journal.org/papers/q-2021-11-17-583/
#
#    Copyright (c) 2019 and later, Jens Koch and Peter Groszkowski
#    All rights reserved.
#
#    This source code is licensed under the BSD-style license found in the
#    LICENSE file in the root directory of this source tree.
############################################################################


import numpy as np
import pytest

import scqubits as scq

from scqubits.core.param_sweep import ParameterSweep


@pytest.mark.usefixtures("num_cpus")
class TestParameterSweep:
    @pytest.fixture(autouse=True)
    def set_tmpdir(self, request):
        setattr(self, "tmpdir", request.getfixturevalue("tmpdir"))

    def initialize(self, num_cpus, evals_count=20):
        # Set up the components / subspaces of our Hilbert space
        scq.settings.MULTIPROC = "pathos"

        tmon1 = scq.TunableTransmon(
            EJmax=40.0,
            EC=0.2,
            d=0.1,
            flux=0.0,
            ng=0.3,
            ncut=40,
            truncated_dim=3,  # after diagonalization, we will keep 3 levels
        )

        tmon2 = scq.TunableTransmon(
            EJmax=15.0, EC=0.15, d=0.2, flux=0.0, ng=0.0, ncut=30, truncated_dim=3
        )

        resonator = scq.Oscillator(
            E_osc=4.5, truncated_dim=4  # up to 3 photons (0,1,2,3)
        )

        hilbertspace = scq.HilbertSpace([tmon1, tmon2, resonator])

        g1 = 0.1  # coupling resonator-CPB1 (without charge matrix elements)
        g2 = 0.2  # coupling resonator-CPB2 (without charge matrix elements)

        hilbertspace.add_interaction(
            g_strength=g1,
            op1=tmon1.n_operator,
            op2=resonator.creation_operator,
            add_hc=True,
        )

        hilbertspace.add_interaction(
            g_strength=g2,
            op1=tmon2.n_operator,
            op2=resonator.creation_operator,
            add_hc=True,
        )

        # Set up parameter name and values
        pname1 = "flux"
        flux_vals = np.linspace(0.0, 2.0, 11)
        pname2 = "ng"
        ng_vals = np.linspace(-0.5, 0.5, 3)

        # combine into a dictionary
        paramvals_by_name = {pname1: flux_vals, pname2: ng_vals}

        area_ratio = 1.2

        def update_hilbertspace(
            flux, ng
        ):  # function that defines how Hilbert space components are updated
            tmon1.flux = flux
            tmon2.flux = area_ratio * flux
            tmon2.ng = ng

        # dictionary with information on which subsystems are affected by changing parameters
        subsys_update_info = {pname1: [tmon1, tmon2], pname2: [tmon2]}

        # create the ParameterSweep
        sweep = ParameterSweep(
            hilbertspace=hilbertspace,
            paramvals_by_name=paramvals_by_name,
            update_hilbertspace=update_hilbertspace,
            evals_count=evals_count,
            subsys_update_info=subsys_update_info,
            num_cpus=num_cpus,
        )
        return sweep

    def test_ParameterSweep(self, num_cpus):
        sweep = self.initialize(num_cpus)

        calculated_evals = sweep["evals"][1, 1]

        reference_evals = np.array(
            [
                -38.24067872,
                -34.80636811,
                -33.70287551,
                -31.50027076,
                -31.23467726,
                -30.28547786,
                -29.16544659,
                -27.80039104,
                -27.08317259,
                -26.69778263,
                -25.76389721,
                -24.59864846,
                -24.49435409,
                -24.43639473,
                -23.2803766,
                -22.63621727,
                -22.16084701,
                -21.00224623,
                -21.00053542,
                -20.07811164,
            ]
        )
        assert np.allclose(reference_evals, calculated_evals)

    def test_ParameterSweep_fileIO(self, num_cpus):
        sweep = self.initialize(num_cpus)
        sweep.filewrite(self.tmpdir + "test.h5")
        sweep_copy = scq.read(self.tmpdir + "test.h5")

    def test_ParameterSweep_labeling(self, num_cpus):
        sweep = self.initialize(num_cpus, evals_count=36)

        # DE ordering is already generated by default
        # we compare 9th state only
        ref_indices_DE = np.array(
            [
                [8, 8, 8],
                [8, 8, 8],
                [8, 8, 8],
                [11, 11, 11],
                [9, 9, 9],
                [8, 8, 8],
                [6, 6, 6],
                [11, 11, 11],
                [None, None, None],
                [9, 9, 9],
                [7, 7, 7],
            ],
            dtype=object,
        )
        assert np.all(sweep["dressed_indices"][..., 9] == ref_indices_DE)

        # BE ordering
        indices_BE10 = sweep.generate_lookup(
            ordering="BE", subsys_priority=[2, 1, 0], BEs_count=10
        )
        ref_indices_BE10 = np.array(
            [
                [8, 8, 8],
                [8, 8, 8],
                [8, 8, 8],
                [None, None, None],
                [9, 9, 9],
                [8, 8, 8],
                [6, 6, 6],
                [None, None, None],
                [None, None, None],
                [9, 9, 9],
                [7, 7, 7],
            ],
            dtype=object,
        )
        assert np.all(indices_BE10[..., 9] == ref_indices_BE10)

        # LX ordering
        indices_LX = sweep.generate_lookup(ordering="LX", subsys_priority=[2, 1, 0])
        ref_indices_LX = np.array(
            [
                [8, 8, 8],
                [8, 8, 8],
                [8, 8, 8],
                [11, 11, 11],
                [9, 9, 9],
                [8, 8, 8],
                [6, 6, 6],
                [11, 11, 11],
                [11, 11, 11],
                [9, 9, 9],
                [7, 7, 7],
            ],
            dtype=object,
        )
        assert np.all(indices_LX[..., 9] == ref_indices_LX)

    def test_validate_states_accepts_dressed_index(self, num_cpus):
        """Regression: ``_validate_states`` must accept ``int`` (dressed-state
        index) as well as ``tuple`` (bare-product-state label).

        Pre-fix, the Explorer's ``Transitions`` panel crashed with
        ``TypeError: object of type 'int' has no len()`` whenever the
        ``initial_bare_dressed_toggle`` widget was switched to "by
        dressed index", because ``plot_transitions`` passes the
        integer index straight into ``_validate_states``.
        """
        sweep = self.initialize(num_cpus)

        # int form: dressed-state index (no crash).
        sweep._validate_states(initial=0, final=None)
        sweep._validate_states(initial=3, final=5)

        # None form: "no state specified" (the default) must be a no-op.
        sweep._validate_states(initial=None, final=None)

        # tuple form: bare-product-state label (existing behavior preserved).
        sweep._validate_states(initial=(0, 0, 0), final=None)
        sweep._validate_states(initial=(0, 0, 0), final=(1, 0, 0))

        # Mixed: tuple initial, int final.
        sweep._validate_states(initial=(0, 0, 0), final=3)

        # Tuple-shape errors still fire.
        with pytest.raises(ValueError, match="number of subsystems"):
            sweep._validate_states(initial=(0, 0), final=None)


class TestProgressBarParallelDispatch:
    """Progress bars must never be stored on the ParameterSweep instance.

    A tqdm bar holds an unpicklable lock (and, as a notebook widget, an ipywidgets
    comm), while the worker tasks pickle ``self`` during parallel dispatch. With the
    deferred-close path active (IN_IPYTHON) a multi-subsystem ``num_cpus > 1`` sweep
    pickles ``self`` after the first phase bar would have been registered, so storing
    bars on the instance breaks the sweep.
    """

    def test_parallel_multisubsys_sweep_with_bars_pickles(self, monkeypatch):
        monkeypatch.setattr(scq.settings, "IN_IPYTHON", True)
        monkeypatch.setattr(scq.settings, "PROGRESSBAR_DISABLED", False)

        q1 = scq.TunableTransmon(
            EJmax=30.0, EC=0.2, d=0.1, flux=0.0, ng=0.0, ncut=30, truncated_dim=4
        )
        q2 = scq.TunableTransmon(
            EJmax=20.0, EC=0.2, d=0.1, flux=0.0, ng=0.0, ncut=30, truncated_dim=4
        )
        hs = scq.HilbertSpace([q1, q2])
        hs.add_interaction(g_strength=0.1, op1=q1.n_operator, op2=q2.n_operator)

        def update(flux):
            q1.flux = flux

        sweep = scq.ParameterSweep(
            hilbertspace=hs,
            paramvals_by_name={"flux": np.linspace(0.0, 0.4, 6)},
            update_hilbertspace=update,
            evals_count=8,
            num_cpus=2,  # real parallel dispatch -> pickles self
        )
        # completed without a pickling error, and self retains no progress bars
        assert not hasattr(sweep, "_progress_bars")
        assert sweep["evals"].shape[0] == 6


class TestRunExceptionSafety:
    def test_dispatch_enabled_restored_when_sweep_raises(self, monkeypatch):
        # A sweep that raises mid-run must still restore settings.DISPATCH_ENABLED,
        # or every later sweep in the kernel is silently poisoned.
        monkeypatch.setattr(scq.settings, "DISPATCH_ENABLED", True)
        q = scq.TunableTransmon(
            EJmax=30.0, EC=0.2, d=0.1, flux=0.0, ng=0.0, ncut=20, truncated_dim=3
        )
        hs = scq.HilbertSpace([q])

        def boom(flux):
            raise RuntimeError("boom")

        sweep = scq.ParameterSweep(
            hilbertspace=hs,
            paramvals_by_name={"flux": np.linspace(0.0, 0.4, 4)},
            update_hilbertspace=boom,
            evals_count=3,
            num_cpus=1,
            autorun=False,
        )
        with pytest.raises(RuntimeError, match="boom"):
            sweep.run()
        assert scq.settings.DISPATCH_ENABLED is True

    def test_consume_with_bar_closes_bar_on_exception(self, monkeypatch):
        import scqubits.core.param_sweep as ps_mod

        closed = {"value": False}

        class FakeBar:
            def __init__(self, **kwargs):
                pass

            def update(self, n):
                pass

            def refresh(self):
                pass

            def close(self):
                closed["value"] = True

        monkeypatch.setattr(ps_mod, "tqdm", lambda **kwargs: FakeBar(**kwargs))
        q = scq.TunableTransmon(
            EJmax=30.0, EC=0.2, d=0.1, flux=0.0, ng=0.0, ncut=20, truncated_dim=3
        )
        hs = scq.HilbertSpace([q])
        sweep = scq.ParameterSweep(
            hilbertspace=hs,
            paramvals_by_name={"flux": np.array([0.0, 0.1])},
            update_hilbertspace=lambda f: setattr(q, "flux", f),
            evals_count=3,
            num_cpus=1,
            autorun=False,
        )

        def raising():
            yield 1
            raise RuntimeError("boom")

        with pytest.raises(RuntimeError, match="boom"):
            sweep._consume_with_bar(raising(), 2, "x", [])
        assert closed["value"] is True
