name: black-check-latest
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install latest Black version
        run: pip install black
      - name: Run black --check --diff .
        run: black --check --diff .